import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/overlays/header.overlay";
import Breakcrumb from "@/components/overlays/breakcrumb.overlay";
import Footer from "@/components/overlays/footer.overlay";
import { Toaster } from "@/components/ui/sonner";
import { create } from "zustand";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const useGlobalTheme = create<UseGlobalTheme>((set) => ({
  theme: "dark",
  setTheme: (theme) => set((_s) => ({ theme })),
  toggleTheme: () =>
    set((s) => ({ theme: s.theme === "dark" ? "light" : "dark" })),
}));

type UseGlobalTheme = {
  theme: "dark" | "light";
  setTheme: (theme: "dark" | "light") => void;
  toggleTheme: () => void;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const theme = useGlobalTheme((state) => state.theme);

  return (
    <html lang="en" className="dark">
      <body>
        <Header />
        <Breakcrumb />
        <Toaster />

        <main className="flex justify-center">
          <div className="container border-x border-dashed">{children}</div>
        </main>

        <Footer />
      </body>
    </html>
  );
}
