- name: "Prepare local files"
  hosts: localhost

  vars_files:
    - ../vars/client-vars.yaml

  tasks:
    - name: "Rename local config"
      copy:
        src: "{{ local_project_path }}/src/lib/public-env.ts"
        dest: "{{ local_project_path }}/src/lib/public-env.temp.ts"

    - name: "Replace remote config"
      copy:
        src: "{{ local_project_path }}/src/lib/public-env.prod.ts"
        dest: "{{ local_project_path }}/src/lib/public-env.ts"

    - name: "Build final files"
      command: "npm run build"
      args:
        chdir: "{{ local_project_path }}"

    - name: "Compress files"
      command: "rar a zigma.rar ./.next ./package.json ./package-lock.json ./next.config.ts"
      args:
        chdir: "{{ local_project_path }}"

    - name: "Return local config"
      copy:
        src: "{{ local_project_path }}/src/lib/public-env.temp.ts"
        dest: "{{ local_project_path }}/src/lib/public-env.ts"

    - name: "Remove temp file"
      file:
        path: "{{ local_project_path }}/src/lib/public-env.temp.ts"
        state: "absent"

- name: "Deploy on remote"
  hosts: zigma

  vars_files:
    - ../vars/client-vars.yaml

  tasks:
    - name: "Upload files"
      copy:
        src: "{{ local_rar_file }}"
        dest: "{{ remote_rar_file }}"

    - name: "Extract files"
      command: "unrar x ./zigma.rar -o+"
      args:
        chdir: "{{ remote_project_path }}"

    - name: "Install dependencies"
      npm:
        path: "{{ remote_project_path }}"
        state: present

    - name: "Restart project"
      command: "pm2 restart {{ project_name }}"
